# Generated by Django 3.0 on 2019-12-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default=None, max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(default=None, verbose_name='网站'),
        ),
    ]
